### PR TITLE
Added edge_duration section

### PR DESCRIPTION
**Pull request by Shashank-1234**
Added duration section and functions to parse the instance as well as read and write functions in vrplib to handle problems that has both durations and distances which need to be simultaneously optimised. pyvrp does offer the functionality https://github.com/PyVRP/PyVRP/pull/546 which is not yet implemented in the vrplib.

### CODE REVIEW

**Comment by N-Wouda** [comment]
@leonlan could you have a look at this once you return from your holidays?

**Comment by N-Wouda** [comment]
It's easiest to fix the formatting by setting up pre-commit locally and having it run on all files once. The [PyVRP docs](https://pyvrp.org/dev/contributing.html#setting-up-a-local-installation) about pre-commit should apply here too, I think.

**Comment by leonlan** [comment]
Hi @Shashank-1234, thanks for opening this PR. While PyVRP does support both edge distances and durations, the "original" VRPLIB format based on TSPLIB, CVRPLIB, and LKH-3 does not really make this distinction. We should first address how to include durations in VRPLIB format before supporting this in the `vrplib` package. I'd be happy to discuss this further in #114.

**Comment by Shashank-1234** [comment]
Hi @leonlan, thanks for your comment. Looks like TSPLIB has an option to take in a special function while calculation of EDGE_WEIGHT. User can probably leverage this to also add in the duration of the edge. 
https://tsplib95.readthedocs.io/en/stable/pages/usage.html#special-functions-label

But PyVRP offers a separate attribute for duration and as i understand, it adds distance + duration for cost function. 

Since, PyVRP exposed duration as a separate attribute to the user, i think it makes sense to also support it in the vrplib. Let me know what you think.

**Comment by leonlan** [comment]
> Hi @leonlan, thanks for your comment. Looks like TSPLIB has an option to take in a special function while calculation of EDGE_WEIGHT. User can probably leverage this to also add in the duration of the edge. [tsplib95.readthedocs.io/en/stable/pages/usage.html#special-functions-label](https://tsplib95.readthedocs.io/en/stable/pages/usage.html#special-functions-label)
> 
> But PyVRP offers a separate attribute for duration and as i understand, it adds distance + duration for cost function.
> 
> Since, PyVRP exposed duration as a separate attribute to the user, i think it makes sense to also support it in the vrplib. Let me know what you think.

I'm not opposed to supporting duration matrices in VRPLIB, but there is a bit more context that we need to take into account before supporting it. VRPLIB is a separate project from PyVRP, as VRPLIB is concerned with VRP benchmark instances that go beyond the PyVRP solver. I am currently not aware of any VRP benchmark instances that include travel time/duration matrix data, so before adding support we should first find use cases for it.

**Comment by leonlan** [comment]
I'm closing this PR for now, as adding support for edge durations needs further discussion. Please feel free to open an issue to share use cases and help develop this idea further.

**Pull request closed without merging**
